language: python
python:
  - '3.5'

before_install:
  - sudo apt-get install -qq libblas-dev

install:
  - pip install numpy
  - pip install git+https://github.com/Theano/Theano.git#egg=Theano
  - pip install h5py
  - pip install pyyaml

script:
  - python -m unittest tests/test_generative.py
  - python -m unittest tests/test_networkhelper.py
  - python -m unittest tests/test_sgd_opt.py

