language: python
python:
  - '3.5'
addons:
  apt:
    packages:
      - libblas-dev
env:
  global:
    - CXX=g++-4.8
    - THEANO_FLAGS=cxx=/usr/bin/g++-4.8

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 -y

install:
  - /usr/bin/g++ --version
  - pip install theano
  - pip install h5py
  - pip install pyyaml

script:
  - python -m unittest mlbase/tests/test_generative.py
  - python -m unittest mlbase/tests/test_networkhelper.py
  - python -m unittest mlbase/tests/test_sgd_opt.py

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
